name: Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  check:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Check
        run: |
          yarn install
          yarn check
