name: Deploy

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Build plugin
        run: |
          yarn install
          yarn build
      - name: Build preview
        working-directory: preview
        env:
          CLIENT_ID: efc6c2ca30ec308ce283
          TOKEN_URL: https://polar-falls-16277.herokuapp.com/authenticate/
          METHOD: GET
        run: |
          yarn install
          yarn build
      - name: Deploy preview to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./preview/build
          user_name: Jeroen van den Hout
          user_email: jlvandenhout@gmail.com
